### PR TITLE
feat: First version

### PR DESCRIPTION
**Pull request by yevgenypats**
This is still WIP.

Missing:
[ ] Mock tests
[ ] Concurrency
[ ] Transformations of Sharepoint Types to CloudQuery Types

### CODE REVIEW

**Comment by koltyakov** [comment]
@yevgenypats it looks great! 

I'm not interfere to the places there some gaps preventing a scalability structure wise for now. When I will be applying changes to the plugin I'll amend a few principal things which are not so important in the initial version. And definitely will be commenting what and why is done in a way it should be due to the platform specifics.

Also, what I'd want to amend later is the incremental mode. The platform allows getting what's changed (added, updated, removed, restored) in a robust and very efficient way, as well as continuing sync of a large list from where it stopped. Regarding this, does CloudQuery provide a sync state OOTB approach? To optionally use on a next sync run.

**Comment by koltyakov** [comment]
Hi @yevgenypats should we merged this PR so far? I know that @disq is actively working these days.

**Comment by yevgenypats** [comment]
I just merged @disq PR. I think we can merge it now but will let @disq weigh in if anything else should be done before that?

**Comment by disq** [comment]
Well it seems to work so far... I'm sure we'll find some edge cases and some more types to handle and so on, as we start throwing more "List"s into it.

**Comment by disq** [comment]
Currently we don't handle these types explicitly so they fallback to `TypeJSON`:

```
7:57PM WRN unknown type, assuming JSON field_id=c07b7c34-79bd-4f49-8409-367c5ed35a35 field_title=FieldHyperLink kind=11 module=sharepoint-src table=sharepoint_data_types type=URL
7:57PM WRN unknown type, assuming JSON field_id=716664c5-2385-4e48-be15-2d0c812a7103 field_title=FieldLocation kind=33 module=sharepoint-src table=sharepoint_data_types type=Location
7:57PM WRN unknown type, assuming JSON field_id=fc83d5c5-f61a-4692-9700-592383ee2b55 field_title="FieldLocation: Coordinates" kind=31 module=sharepoint-src table=sharepoint_data_types type=Geolocation
7:57PM WRN unknown type, assuming JSON field_id=d37f2bdb-e8bb-4c55-826a-52d46761e019 field_title=FieldImage kind=34 module=sharepoint-src table=sharepoint_data_types type=Thumbnail
7:57PM WRN unknown type, assuming JSON field_id=8b5d5756-6be4-4856-be55-bcc43ae89706 field_title=FieldManagedMetadataSingle kind=0 module=sharepoint-src table=sharepoint_data_types type=TaxonomyFieldType
7:57PM WRN unknown type, assuming JSON field_id=04582bcd-b682-415d-abde-d3cef4d7de97 field_title=FieldManagedMetadataMulti kind=0 module=sharepoint-src table=sharepoint_data_types type=TaxonomyFieldTypeMulti
```

**Comment by koltyakov** [comment]
Going to merge this now. And play around with code and sync scenarios later on this week. 

Thank you @yevgenypats, @disq you are champs!

**Pull request merged**
